### ISSUE TITLE
Should I enable `editUrl`?

### ISSUE THREAD

**Issue by iamrajiv** [keptn-sandbox/new-keptn-docs-engine#13]
## Description

`editUrl` is a base URL to edit your site. The final URL is computed by `editUrl + relativeDocPath`. Using a function allows more nuanced control for each file. Omitting this variable entirely will disable edit links.

As of now, I have disabled it because the docs will be pulled from another repository so even if `editUrl` is enabled it won't be useful I feel.

After enabling `editUrl` field it will look like this on the page:

<img width="165" alt="Screenshot 2022-07-28 at 11 33 49 PM" src="https://user-images.githubusercontent.com/42106787/181608445-44f0fd0a-7bde-4fca-8258-5630ba6a336f.png">

**Comment by mehabhalodiya** [comment]
For more, go over through Slack discussion: https://keptn.slack.com/archives/C017T4KUAG3/p1659018207268779

**Comment by vadasambar** [comment]
It'd be nice if we could enable `Edit` button on docs which aren't pulled from other repos and disable it on the docs pulled from other repos. Sounds like a nice thing to have if we get it right,
