### ISSUE TITLE
Add Vale linter for doc quality check

### ISSUE THREAD

**Issue by iamrajiv** [keptn-sandbox/new-keptn-docs-engine#19]
## Description

[Vale](https://github.com/errata-ai/vale) is a command-line tool that brings code-like linting to prose life. To integrate Vale into the new documentation engine we need GitHub Action for Vale.

So, we will be using [vale-action](https://github.com/errata-ai/vale-action) which is the official GitHub Action for Vale according to our new documentation engine.

**Comment by vadasambar** [comment]
Questions:
1. Why did we choose Vale? 
2. What are the quality checks that we are supporting right now? And why those checks? (<- we should reach out to the community for feedback around what checks we should be including)
3. Is the vale linter going to block PR merge (it seems to be doing that right now). If yes, is this the strategy going forward and what are the reasons for doing so? 
![image](https://user-images.githubusercontent.com/34534103/185307268-f023850a-e00b-40ce-a556-4c2c473d8a34.png)
